dist: trusty
language: java
jdk:
  - oraclejdk8
before_install:
  - chmod +x postroom/gradlew
  - chmod +x postroom/gradle/wrapper/gradle-wrapper.jar
script:
  - ./postroom/gradlew -b postroom/build.gradle test build