version: "3"
services:
  database:
    image: "postgres:12"
    container_name: "database"
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build:
      context: ./api
    depends_on:
      - database
    container_name: "api"
    ports:
      - "7000:7000"
    environment:
      API_PORT: 7000
      DATABASE_HOST: jdbc:postgresql://database
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
volumes:
  database_data:
