version: "3"
services:
  database:
    image: "postgres:12"
    container_name: "satchel"
    ports:
      - "5432:5432"
    volumes:
      - satchel_data:/var/lib/postgresql/data
      - ./satchel/init.sql:/docker-entrypoint-initdb.d/init.sql
  postroom:
    build:
      context: ./postroom
    depends_on:
      - database
    container_name: "postroom"
    ports:
      - "7000:7000"
volumes:
  satchel_data: