version: "3"
services:
  database:
    image: "postgres:12"
    container_name: "satchel"
    ports:
      - "5432:5432"
    volumes:
      - ./satchel_data:/var/lib/postgresql/data
      - ./satchel/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build:
      context: ./api
    depends_on:
      - database
    container_name: "api"
    ports:
      - "7000:7000"
    environment:
      POSTMAN_PORT: 7000
      SATCHEL_HOST: jdbc:postgresql://satchel
      SATCHEL_PORT: 5432
      SATCHEL_USER: postgres
volumes:
  satchel_data:
